<?php

/*
 * Implements hook_permission()
 */

function demo_permission() {
return array (
              'administer demo module' => array (
                                                 'title' => t('Administer Demo Module'),
                                                  'description' => t('This Module is used to give administer permissions'),                         
),

);

}

/*
 * Implement hook_node_view().
 */

function demo_node_view($node, $view_mode, $langcode) {
                       $node->content['demo_field'] = array(
                       '#type' => 'markup',
                       '#markup' => '<p> '.t('This is the content that you see when u visit a node').'</p>',
                       '#weight' => -10, 

);

krumo($node);
}
