<?php
/*
 * Implements hook_menu().
 */
function menu_magic_menu()
{
  $items                     = array();
  $items['magic']            = array(
    'title' => 'A Little Magic',
    'page callback' => 'menu_magic_basic',
    'access callback' => 'user_access',
    'access arguments' => array(
      'access content'
    )
  );
  $items['magic/%']          = array(
    'title' => 'Even More Magical',
    'page callback' => 'menu_magic_extra',
    'page arguments' => array(
      1
    ),
    'access callback' => 'user_access',
    'access arguments' => array(
      'access content'
    ),
    'file' => 'menu_magic.extra.inc'
  );
  $items['user/%/magic']     = array(
    'title' => 'Magic',
    'description' => 'Magic for users',
    'page callback' => 'menu_magic_user_tab',
    'page arguments' => array(
      1
    ),
    'access callback' => 'user_access',
    'access arguments' => array(
      'administer users'
    ),
    'file' => 'menu_magic.user.inc',
    'type' => MENU_LOCAL_TASK
  );
  $items['node/%node/magic'] = array(
    'title' => 'Magic',
    'description' => 'This can do magical things for users',
    'page callback' => 'menu_magic_node_context',
    'page arguments' => array(
      1
    ),
    'access callback' => 'user_access',
    'access arguments' => array(
      'access content'
    ),
    'file' => 'menu_magic.context.inc',
    'type' => MENU_LOCAL_TASK,
    'context' => MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE
  );
  return $items;
}
function menu_magic_basic()
{
  $content                       = array();
  $content['raw_markup']         = array(
    '#type' => 'markup',
    '#markup' => '<p>' . t('This is truely magical indeed') . '</p>'
  );
  $variables                     = array(
    'path' => 'http://placekitten.com/440/400',
    'alt' => t('This is a magical kitten'),
    'title' => t('This is title')
  );
  $content['themed_data']        = array(
    '#type' => 'markup',
    '#markup' => theme('image', $variables),
    '#prefix' => '<div class = "menu_magic_image".>',
    '#suffix' => '</div>',
    '#attached' => array(
      'css' => array(
        drupal_get_path('module', 'menu_magic') . '/menu_magic.css'
      )
    )
  );
  $content['renderable_element'] = array(
    '#theme' => 'item_list',
    '#title' => t('Magical list'),
    '#items' => array(
      t('This is first item'),
      t('This is second item'),
      t('This is third item'),
      t('The current time is %time.', array(
        '%time' => date('r')
      ))
    ),
    '#cache' => array(
      'key' => array(
        'menu_magic',
        'renderable_element'
      ),
      'bin' => 'cache',
      'expire' => time() + 30,
      'granularity' => DRUPAL_CACHE_PER_PAGE
    )
  );
  return $content;
}

