
<?php
  /*
   *implements hook_menu()
   */
  function menu_magic_menu() {
      $items                     = array();
      $items['magic']            = array(
          'title' => 'A little magic',
          'page callback' => 'menu_magic_basic',
          'access arguments' => array(
              'access control'
          )
      );
      $items['magic/%']          = array(
          'title' => 'Even more magical',
          'page callback' => 'menu_magic_extra',
          'page arguments' => array(
              1
          ),
          'access arguments' => array(
              'access control'
          ),
          'file' => 'menu_magic.extra.inc'
      );
      $items['user/%/magic']     = array(
          'title' => 'Magic',
          'description' => 'magical magic for users',
          'page callback' => 'menu_magic_user_tab',
          'page arguments' => array(
              1
          ),
          'access arguments' => array(
              'administer users'
          ),
          'file' => 'menu_magic.user.inc',
          'type' => MENU_LOCAL_TASK
      );
      //node_load(%);
      $items['node/%node/magic'] = array(
          'title' => 'Magic',
          'description' => 'do amazing and magical things',
          'page callback' => 'menu_magic_code_context',
          'page arguments' => array(
              1
          ),
          'access arguments' => array(
              'access content'
          ),
          'file' => 'menu_magic.context.inc',
          'type' => MENU_LOCAL_TASK,
          'context' => MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE
      );
      return $items;
  }
  function menu_magic_basic() {
      $content                       = array();
      $content['raw_markup']         = array(
          '#type' => 'markup',
          '#markup' => 'truly this is magical!',
          '#prefix' => '<p>',
          '#suffix' => '</p>'
      );
      $variables                     = array(
          'path' => 'http://placekitten.com.s3.amazonaws.com/homepage-samples/408/287.jpg',
          'alt' => t('picture'),
          'title' => t('this is title')
      );
      $content['themed_data']        = array(
          '#type' => 'markup',
          '#markup' => theme('image', $variables),
          '#prefix' => '<div class="menu-magic-image">',
          '#suffix' => '</div>',
          '#attached' => array(
              'css' => array(
                  drupal_get_path('module', 'menu_magic') . '\menu_magic.css'
              )
          )
      );
      $content['renderable_element'] = array(
          '#theme' => 'item_list',
          '#title' => t('ohh its a magic'),
          '#items' => array(
              t('hi'),
              t('hello'),
              t('how r u?'),
              t('the current time is %time', array(
                  '%time' => date('r')
              ))
          ),
          '#cache' => array(
              'keys' => array(
                  'menu_magic',
                  'renderable_array'
              ), //menu_magic:renderable_array
              'bin' => 'cache',
              'expire' => time() + 30
          )
      );
      return $content;
  }

